kind: Pod
apiVersion: v1
metadata:
  name: attacker-privileged-test
  namespace: default
  labels:
    app: normal-app
spec:
  containers:
    - name: attacker-container
      image: alpine:latest
      args: ["sleep", "10000"]
      securityContext:
        runAsUser: 0
        capabilities:
        drop:
          - all
        add:
          - SYS_CHROOT
          - NET_BIND_SERVICE - SETGID
          - SETUID
